### ISSUE TITLE
super layoutSubviews

### ISSUE THREAD

**Issue by jindulys** [jmah/WrapDemo#2]
![screen shot 2015-04-28 at 4 49 36 pm](https://cloud.githubusercontent.com/assets/1540225/7379951/9c2a60de-edc6-11e4-8311-4f435e0739c5.png)
In the file **LabelWrappingSuperview.m**, why do we need the second `[super layoutSubviews]`?

Since **LabelWrappingSuperview**'s super is **UIView**, the implementation of UIView **-layoutSubviews** does nothing, why do we need it?  I tested by commenting it out, the code worked as well.

**Comment by jmah** [comment]
You're correct, it seems the layout system triggers another layout after changing `preferredMaxLayoutWidth`. However `-[UIView layoutSubviews]` definitely does do work.
